type PlateData = Record<string, [string, Record<string, string>] | [string]>;

const plateMappingData: PlateData = {
  B: [
    'JADETABEK',
    {
      U: 'Jakarta Utara',
      B: 'Jakarta Barat',
      P: 'Jakarta Pusat',
      T: 'Jakarta Timur',
      S: 'Jakarta Selatan',
      W: 'Tangerang Selatan, Banten',
      C: 'Tangerang, Banten',
      V: 'Tangerang, Banten',
      G: 'Tangerang, Banten',
      N: 'Tangerang, Banten',
      E: 'Depok, Jawa Barat',
      Z: 'Depok, Jawa Barat',
      F: 'Bekasi, Jawa Barat',
      K: 'Bekasi, Jawa Barat'
    }
  ],
  F: [
    'Jawa Barat',
    {
      A: 'Bogor, Jawa Barat',
      B: 'Bogor, Jawa Barat',
      C: 'Bogor, Jawa Barat',
      D: 'Bogor, Jawa Barat',
      E: 'Bogor, Jawa Barat',
      F: 'Kab. Bogor, Jawa Barat',
      G: 'Kab. Bogor, Jawa Barat',
      H: 'Kab. Bogor, Jawa Barat',
      I: 'Kab. Bogor, Jawa Barat',
      J: 'Kab. Bogor, Jawa Barat',
      K: 'Kab. Bogor, Jawa Barat',
      L: 'Kab. Bogor, Jawa Barat',
      M: 'Kab. Bogor, Jawa Barat',
      N: 'Kab. Bogor, Jawa Barat',
      O: 'Kab. Bogor, Jawa Barat',
      P: 'Kab. Bogor, Jawa Barat',
      R: 'Kab. Bogor, Jawa Barat',
      S: 'Sukabumi, Jawa Barat',
      T: 'Sukabumi, Jawa Barat',
      Q: 'Kab. Sukabumi, Jawa Barat',
      U: 'Kab. Sukabumi, Jawa Barat',
      V: 'Kab. Sukabumi, Jawa Barat',
      W: 'Cianjur, Jawa Barat',
      X: 'Cianjur, Jawa Barat',
      Y: 'Cianjur, Jawa Barat',
      Z: 'Cianjur, Jawa Barat'
    }
  ],
  D: [
    'Jawa Barat',
    {
      A: 'Bandung, Jawa Barat',
      B: 'Bandung, Jawa Barat',
      C: 'Bandung, Jawa Barat',
      D: 'Bandung, Jawa Barat',
      E: 'Bandung, Jawa Barat',
      F: 'Bandung, Jawa Barat',
      G: 'Bandung, Jawa Barat',
      H: 'Bandung, Jawa Barat',
      I: 'Bandung, Jawa Barat',
      J: 'Bandung, Jawa Barat',
      K: 'Bandung, Jawa Barat',
      L: 'Bandung, Jawa Barat',
      M: 'Bandung, Jawa Barat',
      N: 'Bandung, Jawa Barat',
      O: 'Bandung, Jawa Barat',
      P: 'Bandung, Jawa Barat',
      Q: 'Bandung, Jawa Barat',
      R: 'Bandung, Jawa Barat',
      S: 'Cimahi, Jawa Barat',
      T: 'Cimahi, Jawa Barat',
      U: 'Kab. Bandung Barat, Jawa Barat',
      X: 'Kab. Bandung Barat, Jawa Barat',
      Z: 'Kab. Bandung Barat, Jawa Barat',
      V: 'Kab. Bandung, Jawa Barat',
      W: 'Kab. Bandung, Jawa Barat',
      Y: 'Kab. Bandung, Jawa Barat'
    }
  ],
  E: [
    'Jawa Barat',
    {
      A: 'Cirebon, Jawa Barat',
      B: 'Cirebon, Jawa Barat',
      C: 'Cirebon, Jawa Barat',
      D: 'Cirebon, Jawa Barat',
      E: 'Cirebon, Jawa Barat',
      F: 'Cirebon, Jawa Barat',
      G: 'Cirebon, Jawa Barat',
      H: 'Kab. Cirebon, Jawa Barat',
      I: 'Kab. Cirebon, Jawa Barat',
      J: 'Kab. Cirebon, Jawa Barat',
      K: 'Kab. Cirebon, Jawa Barat',
      L: 'Kab. Cirebon, Jawa Barat',
      M: 'Kab. Cirebon, Jawa Barat',
      N: 'Kab. Cirebon, Jawa Barat',
      O: 'Kab. Cirebon, Jawa Barat',
      P: 'Indramayu, Jawa Barat',
      Q: 'Indramayu, Jawa Barat',
      R: 'Indramayu, Jawa Barat',
      S: 'Indramayu, Jawa Barat',
      T: 'Indramayu, Jawa Barat',
      U: 'Majalengka, Jawa Barat',
      V: 'Majalengka, Jawa Barat',
      W: 'Majalengka, Jawa Barat',
      X: 'Majalengka, Jawa Barat',
      Y: 'Kuningan, Jawa Barat',
      Z: 'Kuningan, Jawa Barat'
    }
  ],
  T: [
    'Jawa Barat',
    {
      A: 'Purwakarta, Jawa Barat',
      B: 'Purwakarta, Jawa Barat',
      C: 'Purwakarta, Jawa Barat',
      D: 'Karawang, Jawa Barat',
      E: 'Karawang, Jawa Barat',
      F: 'Karawang, Jawa Barat',
      G: 'Karawang, Jawa Barat',
      H: 'Karawang, Jawa Barat',
      I: 'Karawang, Jawa Barat',
      J: 'Karawang, Jawa Barat',
      K: 'Karawang, Jawa Barat',
      L: 'Karawang, Jawa Barat',
      M: 'Karawang, Jawa Barat',
      N: 'Karawang, Jawa Barat',
      O: 'Karawang, Jawa Barat',
      P: 'Karawang, Jawa Barat',
      Q: 'Karawang, Jawa Barat',
      R: 'Karawang, Jawa Barat',
      S: 'Karawang, Jawa Barat',
      T: 'Subang, Jawa Barat',
      U: 'Subang, Jawa Barat',
      V: 'Subang, Jawa Barat',
      W: 'Subang, Jawa Barat',
      X: 'Subang, Jawa Barat',
      Y: 'Subang, Jawa Barat',
      Z: 'Subang, Jawa Barat'
    }
  ],
  Z: [
    'Jawa Barat',
    {
      A: 'Sumedang, Jawa Barat',
      B: 'Sumedang, Jawa Barat',
      C: 'Sumedang, Jawa Barat',
      D: 'Garut, Jawa Barat',
      E: 'Garut, Jawa Barat',
      F: 'Garut, Jawa Barat',
      G: 'Garut, Jawa Barat',
      H: 'Tasikmalaya, Jawa Barat',
      I: 'Tasikmalaya, Jawa Barat',
      J: 'Tasikmalaya, Jawa Barat',
      K: 'Kab. Tasikmalaya, Jawa Barat',
      L: 'Kab. Tasikmalaya, Jawa Barat',
      M: 'Kab. Tasikmalaya, Jawa Barat',
      N: 'Kab. Tasikmalaya, Jawa Barat',
      O: 'Kab. Tasikmalaya, Jawa Barat',
      P: 'Kab. Tasikmalaya, Jawa Barat',
      Q: 'Kab. Tasikmalaya, Jawa Barat',
      R: 'Kab. Tasikmalaya, Jawa Barat',
      S: 'Kab. Tasikmalaya, Jawa Barat',
      T: 'Ciamis, Jawa Barat',
      U: 'Ciamis, Jawa Barat',
      V: 'Ciamis, Jawa Barat',
      W: 'Pangandaran, Jawa Barat',
      X: 'Banjar, Jawa Barat',
      Y: 'Banjar, Jawa Barat',
      Z: 'Banjar, Jawa Barat'
    }
  ],
  A: [
    'Banten',
    {
      A: 'Serang, Banten',
      B: 'Serang, Banten',
      C: 'Serang, Banten',
      D: 'Serang, Banten',
      E: 'Kab. Serang, Banten',
      F: 'Kab. Serang, Banten',
      G: 'Kab. Serang, Banten',
      H: 'Kab. Serang, Banten',
      I: 'Kab. Serang, Banten',
      J: 'Pandeglang, Banten',
      K: 'Pandeglang, Banten',
      L: 'Pandeglang, Banten',
      M: 'Pandeglang, Banten',
      N: 'Pandeglang, Banten',
      O: 'Cilegon, Banten',
      U: 'Cilegon, Banten',
      P: 'Lebak, Banten',
      Q: 'Lebak, Banten',
      R: 'Lebak, Banten',
      S: 'Lebak, Banten',
      T: 'Lebak, Banten',
      V: 'Kab. Tangerang, Banten',
      W: 'Kab. Tangerang, Banten',
      X: 'Kab. Tangerang, Banten',
      Y: 'Kab. Tangerang, Banten',
      Z: 'Kab. Tangerang, Banten'
    }
  ],
  DK: [
    'Bali',
    {
      A: 'Denpasar, Bali',
      B: 'Denpasar, Bali',
      C: 'Denpasar, Bali',
      D: 'Denpasar, Bali',
      E: 'Denpasar, Bali',
      I: 'Denpasar, Bali',
      Q: 'Denpasar, Bali',
      X: 'Denpasar, Bali',
      Y: 'Denpasar, Bali',
      F: 'Badung, Bali',
      J: 'Badung, Bali',
      O: 'Badung, Bali',
      G: 'Tabanan, Bali',
      H: 'Tabanan, Bali',
      K: 'Gianyar, Bali',
      L: 'Gianyar, Bali',
      M: 'Klungkung, Bali',
      N: 'Klungkung, Bali',
      P: 'Bangli, Bali',
      R: 'Bangli, Bali',
      S: 'Karangasem, Bali',
      T: 'Karangasem, Bali',
      U: 'Buleleng, Bali',
      V: 'Buleleng, Bali',
      W: 'Jembrana, Bali',
      Z: 'Jembrana, Bali'
    }
  ],
  L: ['Surabaya, Jawa Timur'],
  M: [
    'Jawa Timur',
    {
      A: 'Pamekasan, Jawa Timur',
      B: 'Pamekasan, Jawa Timur',
      C: 'Pamekasan, Jawa Timur',
      D: 'Pamekasan, Jawa Timur',
      E: 'Pamekasan, Jawa Timur',
      F: 'Pamekasan, Jawa Timur',
      G: 'Pamekasan, Jawa Timur',
      H: 'Bangkalan, Jawa Timur',
      I: 'Bangkalan, Jawa Timur',
      J: 'Bangkalan, Jawa Timur',
      K: 'Bangkalan, Jawa Timur',
      L: 'Bangkalan, Jawa Timur',
      M: 'Bangkalan, Jawa Timur',
      N: 'Bangkalan, Jawa Timur',
      O: 'Sampang, Jawa Timur',
      P: 'Sampang, Jawa Timur',
      Q: 'Sampang, Jawa Timur',
      R: 'Sampang, Jawa Timur',
      S: 'Sampang, Jawa Timur',
      T: 'Sampang, Jawa Timur',
      U: 'Sumenep, Jawa Timur',
      V: 'Sumenep, Jawa Timur',
      W: 'Sumenep, Jawa Timur',
      X: 'Sumenep, Jawa Timur',
      Y: 'Sumenep, Jawa Timur',
      Z: 'Sumenep, Jawa Timur'
    }
  ],
  N: [
    'Jawa Timur',
    {
      A: 'Malang, Jawa Timur',
      B: 'Malang, Jawa Timur',
      C: 'Malang, Jawa Timur',
      E: 'Malang, Jawa Timur',
      D: 'Kab. Malang, Jawa Timur',
      F: 'Kab. Malang, Jawa Timur',
      G: 'Kab. Malang, Jawa Timur',
      H: 'Kab. Malang, Jawa Timur',
      I: 'Kab. Malang, Jawa Timur',
      J: 'Kab. Malang, Jawa Timur',
      K: 'Batu, Jawa Timur',
      L: 'Batu, Jawa Timur',
      M: 'Kab. Probolinggo, Jawa Timur',
      N: 'Kab. Probolinggo, Jawa Timur',
      P: 'Kab. Probolinggo, Jawa Timur',
      Q: 'Probolinggo, Jawa Timur',
      R: 'Probolinggo, Jawa Timur',
      S: 'Probolinggo, Jawa Timur',
      O: 'Kab. Pasuruan, Jawa Timur',
      T: 'Kab. Pasuruan, Jawa Timur',
      W: 'Kab. Pasuruan, Jawa Timur',
      V: 'Pasuruan, Jawa Timur',
      X: 'Pasuruan, Jawa Timur',
      U: 'Lumajang, Jawa Timur',
      Y: 'Lumajang, Jawa Timur',
      Z: 'Lumajang, Jawa Timur'
    }
  ],
  DA: [
    'Kalimantan Selatan',
    {
      A: 'Banjarmasin, Kalimantan Selatan',
      C: 'Banjarmasin, Kalimantan Selatan',
      I: 'Banjarmasin, Kalimantan Selatan',
      J: 'Banjarmasin, Kalimantan Selatan',
      N: 'Banjarmasin, Kalimantan Selatan',
      O: 'Banjarmasin, Kalimantan Selatan',
      S: 'Banjarmasin, Kalimantan Selatan',
      T: 'Banjarmasin, Kalimantan Selatan',
      V: 'Banjarmasin, Kalimantan Selatan',
      W: 'Banjarmasin, Kalimantan Selatan',
      X: 'Banjarmasin, Kalimantan Selatan',
      B: 'Banjar, Kalimantan Selatan',
      Q: 'Banjar, Kalimantan Selatan',
      D: 'Hulu Sungai Selatan, Kalimantan Selatan',
      E: 'Hulu Sungai Tengah, Kalimantan Selatan',
      F: 'Hulu Sungai Utara, Kalimantan Selatan',
      G: 'Kota Baru, Kalimantan Selatan',
      H: 'Tabalong, Kalimantan Selatan',
      U: 'Tabalong, Kalimantan Selatan',
      K: 'Tapin, Kalimantan Selatan',
      L: 'Tanah Laut, Kalimantan Selatan',
      M: 'Barito Kuala, Kalimantan Selatan',
      P: 'Banjarbaru, Kalimantan Selatan',
      R: 'Banjarbaru, Kalimantan Selatan',
      Y: 'Balangan, Kalimantan Selatan',
      Z: 'Tanah Bumbu, Kalimantan Selatan'
    }
  ],
  KH: [
    'Kalimantan Tengah',
    {
      A: 'Palangkaraya, Kalimantan Tengah',
      T: 'Palangkaraya, Kalimantan Tengah',
      Y: 'Palangkaraya, Kalimantan Tengah',
      B: 'Kapuas, Kalimantan Tengah',
      C: 'Kapuas, Kalimantan Tengah',
      D: 'Barito Selatan, Kalimantan Tengah',
      E: 'Barito Utara, Kalimantan Tengah',
      F: 'Kotawaringin Timur, Kalimantan Tengah',
      L: 'Kotawaringin Timur, Kalimantan Tengah',
      W: 'Kotawaringin Timur, Kalimantan Tengah',
      G: 'Kotawaringin Barat, Kalimantan Tengah',
      V: 'Kotawaringin Barat, Kalimantan Tengah',
      H: 'Gunung Mas, Kalimantan Tengah',
      J: 'Pulang Pisau, Kalimantan Tengah',
      K: 'Barito Timur, Kalimantan Tengah',
      M: 'Murung Raya, Kalimantan Tengah',
      N: 'Katingan, Kalimantan Tengah',
      U: 'Katingan, Kalimantan Tengah',
      P: 'Seruyan, Kalimantan Tengah',
      R: 'Lamandau, Kalimantan Tengah',
      S: 'Sukamara, Kalimantan Tengah'
    }
  ],
  KT: [
    'Kalimantan Timur',
    {
      A: 'Balikpapan, Kalimantan Timur',
      K: 'Balikpapan, Kalimantan Timur',
      L: 'Balikpapan, Kalimantan Timur',
      Y: 'Balikpapan, Kalimantan Timur',
      Z: 'Balikpapan, Kalimantan Timur',
      B: 'Samarinda, Kalimantan Timur',
      I: 'Samarinda, Kalimantan Timur',
      M: 'Samarinda, Kalimantan Timur',
      N: 'Samarinda, Kalimantan Timur',
      W: 'Samarinda, Kalimantan Timur',
      X: 'Samarinda, Kalimantan Timur',
      C: 'Kutai Kartanegara, Kalimantan Timur',
      O: 'Kutai Kartanegara, Kalimantan Timur',
      U: 'Bontang, Kalimantan Timur',
      Q: 'Bontang, Kalimantan Timur',
      E: 'Paser, Kalimantan Timur',
      G: 'Berau, Kalimantan Timur',
      P: 'Kutai Barat, Kalimantan Timur',
      R: 'Kutai Timur, Kalimantan Timur',
      V: 'Penajam Paser Utara, Kalimantan Timur'
    }
  ],
  KB: [
    'Kalimantan Barat',
    {
      A: 'Pontianak, Kalimantan Barat',
      Q: 'Pontianak, Kalimantan Barat',
      S: 'Pontianak, Kalimantan Barat',
      W: 'Pontianak, Kalimantan Barat',
      B: 'Mempawah, Kalimantan Barat',
      C: 'Singkawang, Kalimantan Barat',
      D: 'Sanggau, Kalimantan Barat',
      E: 'Sintang, Kalimantan Barat',
      F: 'Kapuas Hulu, Kalimantan Barat',
      G: 'Ketapang, Kalimantan Barat',
      H: 'Melawi, Kalimantan Barat',
      K: 'Bengkayang, Kalimantan Barat',
      L: 'Landak, Kalimantan Barat',
      M: 'Kubu Raya, Kalimantan Barat',
      P: 'Sambas, Kalimantan Barat',
      V: 'Sekadau, Kalimantan Barat',
      Z: 'Kayong Utara, Kalimantan Barat'
    }
  ],
  DR: [
    'Nusa Tenggara Barat',
    {
      A: 'Mataram, NTB',
      B: 'Mataram, NTB',
      C: 'Mataram, NTB',
      D: 'Mataram, NTB',
      E: 'Mataram, NTB',
      H: 'Lombok Barat, NTB',
      J: 'Lombok Barat, NTB',
      K: 'Lombok Barat, NTB',
      L: 'Lombok Timur, NTB',
      S: 'Lombok Tengah, NTB'
    }
  ],
  EA: [
    'Nusa Tenggara Barat',
    {
      A: 'Sumbawa, NTB',
      H: 'Sumbawa Barat, NTB',
      R: 'Dompu, NTB',
      S: 'Bima, NTB',
      X: 'Kab. Bima, NTB',
      Y: 'Kab. Bima, NTB'
    }
  ],
  DB: [
    'Sulawesi Utara',
    {
      A: 'Manado, Sulawesi Utara',
      L: 'Manado, Sulawesi Utara',
      M: 'Manado, Sulawesi Utara',
      R: 'Manado, Sulawesi Utara',
      B: 'Minahasa, Sulawesi Utara',
      C: 'Bitung, Sulawesi Utara',
      D: 'Bolaang Mongondow, Sulawesi Utara',
      E: 'Minahasa Selatan, Sulawesi Utara',
      F: 'Minahasa Utara, Sulawesi Utara',
      G: 'Tomohon, Sulawesi Utara',
      H: 'Bolaang Mongondow Utara, Sulawesi Utara',
      J: 'Minahasa Tenggara, Sulawesi Utara',
      K: 'Kotamobagu, Sulawesi Utara',
      N: 'Bolaang Mongondow Timur, Sulawesi Utara',
      P: 'Bolaang Mongondow Selatan, Sulawesi Utara'
    }
  ],
  DN: [
    'Sulawesi Tengah',
    {
      A: 'Palu, Sulawesi Tengah',
      V: 'Palu, Sulawesi Tengah',
      Y: 'Palu, Sulawesi Tengah',
      B: 'Donggala, Sulawesi Tengah',
      C: 'Banggai, Sulawesi Tengah',
      R: 'Banggai, Sulawesi Tengah',
      D: 'Toli-Toli, Sulawesi Tengah',
      E: 'Poso, Sulawesi Tengah',
      F: 'Buol, Sulawesi Tengah',
      G: 'Morowali, Sulawesi Tengah',
      H: 'Banggai Kepulauan, Sulawesi Tengah',
      J: 'Parigi Moutong, Sulawesi Tengah',
      K: 'Parigi Moutong, Sulawesi Tengah',
      L: 'Tojo Una-Una, Sulawesi Tengah',
      M: 'Sigi, Sulawesi Tengah',
      N: 'Banggai Laut, Sulawesi Tengah',
      U: 'Morowali Utara, Sulawesi Tengah'
    }
  ],
  DD: [
    'Sulawesi Selatan',
    {
      A: 'Makassar, Sulawesi Selatan',
      K: 'Makassar, Sulawesi Selatan',
      Q: 'Makassar, Sulawesi Selatan',
      B: 'Gowa, Sulawesi Selatan',
      L: 'Gowa, Sulawesi Selatan',
      C: 'Takalar, Sulawesi Selatan',
      D: 'Maros, Sulawesi Selatan',
      E: 'Pangkajene dan Kepulauan, Sulawesi Selatan',
      F: 'Bantaeng, Sulawesi Selatan',
      G: 'Jeneponto, Sulawesi Selatan',
      H: 'Bulukumba, Sulawesi Selatan',
      J: 'Selayar, Sulawesi Selatan'
    }
  ],
  PA: [
    'Papua',
    {
      A: 'Jayapura, Papua',
      B: 'Jayawijaya, Papua',
      C: 'Paniai, Papua',
      D: 'Mimika, Papua',
      E: 'Nabire, Papua',
      G: 'Merauke, Papua',
      J: 'Kab. Jayapura, Papua',
      K: 'Biak Numfor, Papua',
      L: 'Kepulauan Yapen, Papua',
      P: 'Puncak Jaya, Papua'
    }
  ],
  G: [
    'Jawa Tengah',
    {
      A: 'Pekalongan, Jawa Tengah',
      H: 'Pekalongan, Jawa Tengah',
      S: 'Pekalongan, Jawa Tengah',
      B: 'Kab. Pekalongan, Jawa Tengah',
      K: 'Kab. Pekalongan, Jawa Tengah',
      O: 'Kab. Pekalongan, Jawa Tengah',
      T: 'Kab. Pekalongan, Jawa Tengah',
      C: 'Batang, Jawa Tengah',
      L: 'Batang, Jawa Tengah',
      V: 'Batang, Jawa Tengah',
      X: 'Batang, Jawa Tengah',
      D: 'Pemalang, Jawa Tengah',
      I: 'Pemalang, Jawa Tengah',
      M: 'Pemalang, Jawa Tengah',
      W: 'Pemalang, Jawa Tengah',
      E: 'Tegal, Jawa Tengah',
      N: 'Tegal, Jawa Tengah',
      Y: 'Tegal, Jawa Tengah',
      F: 'Kab. Tegal, Jawa Tengah',
      P: 'Kab. Tegal, Jawa Tengah',
      Q: 'Kab. Tegal, Jawa Tengah',
      Z: 'Kab. Tegal, Jawa Tengah',
      G: 'Brebes, Jawa Tengah',
      J: 'Brebes, Jawa Tengah',
      R: 'Brebes, Jawa Tengah',
      U: 'Brebes, Jawa Tengah'
    }
  ],
  H: [
    'Jawa Tengah',
    {
      A: 'Semarang, Jawa Tengah',
      F: 'Semarang, Jawa Tengah',
      G: 'Semarang, Jawa Tengah',
      H: 'Semarang, Jawa Tengah',
      P: 'Semarang, Jawa Tengah',
      Q: 'Semarang, Jawa Tengah',
      R: 'Semarang, Jawa Tengah',
      S: 'Semarang, Jawa Tengah',
      W: 'Semarang, Jawa Tengah',
      X: 'Semarang, Jawa Tengah',
      Y: 'Semarang, Jawa Tengah',
      Z: 'Semarang, Jawa Tengah',
      B: 'Salatiga, Jawa Tengah',
      K: 'Salatiga, Jawa Tengah',
      O: 'Salatiga, Jawa Tengah',
      T: 'Salatiga, Jawa Tengah',
      C: 'Kab. Semarang, Jawa Tengah',
      I: 'Kab. Semarang, Jawa Tengah',
      L: 'Kab. Semarang, Jawa Tengah',
      V: 'Kab. Semarang, Jawa Tengah',
      D: 'Kendal, Jawa Tengah',
      M: 'Kendal, Jawa Tengah',
      U: 'Kendal, Jawa Tengah',
      E: 'Demak, Jawa Tengah',
      J: 'Demak, Jawa Tengah',
      N: 'Demak, Jawa Tengah'
    }
  ],
  K: [
    'Jawa Tengah',
    {
      A: 'Pati, Jawa Tengah',
      G: 'Pati, Jawa Tengah',
      H: 'Pati, Jawa Tengah',
      S: 'Pati, Jawa Tengah',
      U: 'Pati, Jawa Tengah',
      B: 'Kudus, Jawa Tengah',
      K: 'Kudus, Jawa Tengah',
      O: 'Kudus, Jawa Tengah',
      R: 'Kudus, Jawa Tengah',
      T: 'Kudus, Jawa Tengah',
      C: 'Jepara, Jawa Tengah',
      L: 'Jepara, Jawa Tengah',
      Q: 'Jepara, Jawa Tengah',
      V: 'Jepara, Jawa Tengah',
      D: 'Rembang, Jawa Tengah',
      I: 'Rembang, Jawa Tengah',
      M: 'Rembang, Jawa Tengah',
      W: 'Rembang, Jawa Tengah',
      E: 'Blora, Jawa Tengah',
      N: 'Blora, Jawa Tengah',
      X: 'Blora, Jawa Tengah',
      Y: 'Blora, Jawa Tengah',
      F: 'Grobogan, Jawa Tengah',
      J: 'Grobogan, Jawa Tengah',
      P: 'Grobogan, Jawa Tengah',
      Z: 'Grobogan, Jawa Tengah'
    }
  ],
  P: [
    'Jawa Timur',
    {
      A: 'Bondowoso, Jawa Timur',
      B: 'Bondowoso, Jawa Timur',
      C: 'Bondowoso, Jawa Timur',
      D: 'Bondowoso, Jawa Timur',
      E: 'Situbondo, Jawa Timur',
      F: 'Situbondo, Jawa Timur',
      G: 'Situbondo, Jawa Timur',
      H: 'Situbondo, Jawa Timur',
      I: 'Situbondo, Jawa Timur',
      J: 'Situbondo, Jawa Timur',
      K: 'Jember, Jawa Timur',
      L: 'Jember, Jawa Timur',
      M: 'Jember, Jawa Timur',
      N: 'Jember, Jawa Timur',
      O: 'Jember, Jawa Timur',
      P: 'Jember, Jawa Timur',
      Q: 'Jember, Jawa Timur',
      R: 'Jember, Jawa Timur',
      S: 'Jember, Jawa Timur',
      T: 'Jember, Jawa Timur',
      U: 'Banyuwangi, Jawa Timur',
      V: 'Banyuwangi, Jawa Timur',
      W: 'Banyuwangi, Jawa Timur',
      X: 'Banyuwangi, Jawa Timur',
      Y: 'Banyuwangi, Jawa Timur',
      Z: 'Banyuwangi, Jawa Timur'
    }
  ],
  S: [
    'Jawa Timur',
    {
      A: 'Bojonegoro, Jawa Timur',
      B: 'Bojonegoro, Jawa Timur',
      C: 'Bojonegoro, Jawa Timur',
      D: 'Bojonegoro, Jawa Timur',
      E: 'Tuban, Jawa Timur',
      F: 'Tuban, Jawa Timur',
      G: 'Tuban, Jawa Timur',
      H: 'Tuban, Jawa Timur',
      I: 'Lamongan, Jawa Timur',
      J: 'Lamongan, Jawa Timur',
      K: 'Lamongan, Jawa Timur',
      L: 'Lamongan, Jawa Timur',
      M: 'Kab. Mojokerto, Jawa Timur',
      N: 'Kab. Mojokerto, Jawa Timur',
      O: 'Kab. Mojokerto, Jawa Timur',
      P: 'Kab. Mojokerto, Jawa Timur',
      Q: 'Kab. Mojokerto, Jawa Timur',
      R: 'Kab. Mojokerto, Jawa Timur',
      S: 'Mojokerto, Jawa Timur',
      T: 'Mojokerto, Jawa Timur',
      U: 'Mojokerto, Jawa Timur',
      V: 'Mojokerto, Jawa Timur',
      W: 'Jombang, Jawa Timur',
      X: 'Jombang, Jawa Timur',
      Y: 'Jombang, Jawa Timur',
      Z: 'Jombang, Jawa Timur'
    }
  ],
  AG: [
    'Jawa Timur',
    {
      A: 'Kediri, Jawa Timur',
      B: 'Kediri, Jawa Timur',
      C: 'Kediri, Jawa Timur',
      D: 'Kediri, Jawa Timur',
      E: 'Kediri, Jawa Timur',
      F: 'Kediri, Jawa Timur',
      G: 'Kab. Kediri, Jawa Timur',
      H: 'Kab. Kediri, Jawa Timur',
      I: 'Kab. Kediri, Jawa Timur',
      J: 'Kab. Kediri, Jawa Timur',
      K: 'Kab. Kediri, Jawa Timur',
      L: 'Kab. Kediri, Jawa Timur',
      M: 'Kab. Kediri, Jawa Timur',
      N: 'Ngawi, Jawa Timur',
      O: 'Ngawi, Jawa Timur',
      P: 'Ngawi, Jawa Timur',
      Q: 'Ngawi, Jawa Timur',
      R: 'Ngawi, Jawa Timur',
      S: 'Ngawi, Jawa Timur',
      T: 'Kab. Madiun, Jawa Timur',
      U: 'Kab. Madiun, Jawa Timur',
      V: 'Kab. Madiun, Jawa Timur',
      W: 'Madiun, Jawa Timur',
      X: 'Madiun, Jawa Timur',
      Y: 'Madiun, Jawa Timur',
      Z: 'Madiun, Jawa Timur'
    }
  ],
  W: [
    'Jawa Timur',
    {
      A: 'Gresik, Jawa Timur',
      B: 'Gresik, Jawa Timur',
      C: 'Gresik, Jawa Timur',
      D: 'Gresik, Jawa Timur',
      E: 'Gresik, Jawa Timur',
      F: 'Gresik, Jawa Timur',
      G: 'Gresik, Jawa Timur',
      H: 'Gresik, Jawa Timur',
      I: 'Gresik, Jawa Timur',
      J: 'Gresik, Jawa Timur',
      K: 'Gresik, Jawa Timur',
      L: 'Gresik, Jawa Timur',
      M: 'Gresik, Jawa Timur',
      N: 'Sidoarjo, Jawa Timur',
      O: 'Sidoarjo, Jawa Timur',
      P: 'Sidoarjo, Jawa Timur',
      Q: 'Sidoarjo, Jawa Timur',
      R: 'Sidoarjo, Jawa Timur',
      S: 'Sidoarjo, Jawa Timur',
      T: 'Sidoarjo, Jawa Timur',
      U: 'Sidoarjo, Jawa Timur',
      V: 'Sidoarjo, Jawa Timur',
      W: 'Sidoarjo, Jawa Timur',
      X: 'Sidoarjo, Jawa Timur',
      Y: 'Sidoarjo, Jawa Timur',
      Z: 'Sidoarjo, Jawa Timur'
    }
  ],
  BB: [
    'Sumatera Utara',
    {
      A: 'Sibolga, Sumatera Utara',
      L: 'Sibolga, Sumatera Utara',
      M: 'Sibolga, Sumatera Utara',
      B: 'Tapanuli Utara, Sumatera Utara',
      C: 'Samosir, Sumatera Utara',
      D: 'Humbang Hasundutan, Sumatera Utara',
      E: 'Toba Samosir, Sumatera Utara',
      F: 'Padang Sidempuan, Sumatera Utara',
      H: 'Padang Sidempuan, Sumatera Utara',
      G: 'Tapanuli Selatan, Sumatera Utara',
      J: 'Padang Lawas, Sumatera Utara',
      K: 'Padang Lawas Utara, Sumatera Utara',
      N: 'Tapanuli Tengah, Sumatera Utara',
      Q: 'Nias Utara, Sumatera Utara',
      R: 'Mandailing Natal, Sumatera Utara',
      T: 'Gunungsitoli, Sumatera Utara',
      U: 'Nias Barat, Sumatera Utara',
      V: 'Nias, Sumatera Utara',
      W: 'Nias Selatan, Sumatera Utara',
      Y: 'Dairi, Sumatera Utara',
      Z: 'Pakpak Bharat, Sumatera Utara'
    }
  ],
  BK: [
    'Sumatera Utara',
    {
      A: 'Medan, Sumatera Utara',
      B: 'Medan, Sumatera Utara',
      C: 'Medan, Sumatera Utara',
      D: 'Medan, Sumatera Utara',
      E: 'Medan, Sumatera Utara',
      F: 'Medan, Sumatera Utara',
      G: 'Medan, Sumatera Utara',
      H: 'Medan, Sumatera Utara',
      I: 'Medan, Sumatera Utara',
      K: 'Medan, Sumatera Utara',
      L: 'Medan, Sumatera Utara',
      J: 'Labuhanbatu Utara, Sumatera Utara',
      M: 'Deli Serdang, Sumatera Utara',
      N: 'Tebing Tinggi, Sumatera Utara',
      O: 'Batubara, Sumatera Utara',
      P: 'Langkat, Sumatera Utara',
      Q: 'Tanjung Balai, Sumatera Utara',
      R: 'Binjai, Sumatera Utara',
      S: 'Karo, Sumatera Utara',
      T: 'Simalungun, Sumatera Utara',
      U: 'Simalungun, Sumatera Utara',
      V: 'Asahan, Sumatera Utara',
      W: 'Pematang Siantar, Sumatera Utara',
      X: 'Serdang Bedagai, Sumatera Utara',
      Y: 'Labuhanbatu, Sumatera Utara',
      Z: 'Labuhanbatu Selatan, Sumatera Utara'
    }
  ],
  BA: [
    'Sumatera Barat',
    {
      A: 'Padang, Sumatera Barat',
      B: 'Padang, Sumatera Barat',
      O: 'Padang, Sumatera Barat',
      Q: 'Padang, Sumatera Barat',
      R: 'Padang, Sumatera Barat',
      C: 'Lima Puluh Kota, Sumatera Barat',
      X: 'Lima Puluh Kota, Sumatera Barat',
      D: 'Pasaman, Sumatera Barat',
      E: 'Tanah Datar, Sumatera Barat',
      F: 'Padang Pariaman, Sumatera Barat',
      G: 'Pesisir Selatan, Sumatera Barat',
      I: 'Pesisir Selatan, Sumatera Barat',
      H: 'Solok, Sumatera Barat',
      J: 'Sawahlunto, Sumatera Barat',
      K: 'Sijunjung, Sumatera Barat',
      L: 'Bukittinggi, Sumatera Barat',
      M: 'Payakumbuh, Sumatera Barat',
      N: 'Padang Panjang, Sumatera Barat',
      P: 'Solok, Sumatera Barat',
      S: 'Pasaman Barat, Sumatera Barat',
      T: 'Agam, Sumatera Barat',
      Z: 'Agam, Sumatera Barat',
      U: 'Kepulauan Mentawai, Sumatera Barat',
      V: 'Dharmasraya, Sumatera Barat',
      W: 'Pariaman, Sumatera Barat',
      Y: 'Solok Selatan, Sumatera Barat'
    }
  ],
  BM: [
    'Riau',
    {
      A: 'Pekanbaru, Riau',
      J: 'Pekanbaru, Riau',
      L: 'Pekanbaru, Riau',
      N: 'Pekanbaru, Riau',
      Q: 'Pekanbaru, Riau',
      T: 'Pekanbaru, Riau',
      B: 'Indragiri Hulu, Riau',
      V: 'Indragiri Hulu, Riau',
      C: 'Pelalawan, Riau',
      I: 'Pelalawan, Riau',
      D: 'Bengkalis, Riau',
      E: 'Bengkalis, Riau',
      F: 'Kampar, Riau',
      O: 'Kampar, Riau',
      Z: 'Kampar, Riau',
      G: 'Indragiri Hilir, Riau',
      H: 'Dumai, Riau',
      R: 'Dumai, Riau',
      K: 'Kuantan Singingi, Riau',
      X: 'Kepulauan Meranti, Riau',
      M: 'Rokan Hulu, Riau',
      U: 'Rokan Hulu, Riau',
      P: 'Rokan Hilir, Riau',
      W: 'Rokan Hilir, Riau',
      S: 'Siak, Riau',
      Y: 'Siak, Riau'
    }
  ]
};

export function getCityPlateCode(city: string): string | null {
  if (!city) return null;

  const cityLower = city.trim().toLowerCase();

  for (const [plateCode, data] of Object.entries(plateMappingData)) {
    if (!Array.isArray(data)) continue;

    if (data.length === 1) {
      const region = data[0].toLowerCase();
      if (region.includes(cityLower)) {
        return plateCode;
      }
    } else if (data.length === 2) {
      const regionName = data[0].toLowerCase();
      if (regionName.includes(cityLower)) {
        return plateCode;
      }

      const subDistricts = data[1];
      for (const [code, districtName] of Object.entries(subDistricts)) {
        if (districtName.toLowerCase().includes(cityLower)) {
          return plateCode + code;
        }
      }
    }
  }

  return null;
}

export function getPlateCodeAndCity(city: string): { code: string; city: string } | null {
  if (!city) return null;

  const code = getCityPlateCode(city);
  if (!code) return null;

  return {
    code,
    city: city.trim()
  };
}
